import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/seo";

/**
 * Googlebot gets the whole public site — every marketplace listing, category,
 * location and collection page. What it must NOT spend crawl budget on is
 * anything private, transactional, or behind auth: those either redirect to
 * /auth/login (a wasted fetch that reads as a soft 404) or are per-user pages
 * with no search value at all.
 *
 * `?q=` marketplace searches are disallowed rather than canonicalised: they
 * are an unbounded URL space generated by a text box, and a crawler wandering
 * it would bury the real listing pages. Category and location browsing has
 * proper crawlable paths instead (/marketplace/furniture/ngong-road).
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: [
        "/account",
        "/account/",
        "/auth/",
        "/checkout",
        "/checkout/",
        "/sell/post",
        "/sell/edit",
        "/api/",
        "/feed/",
        "/marketplace?q=",
        "/*?q=",
      ],
    },
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
